"""add exam_date to subjects

Revision ID: 344fc75860e6
Revises: 8f61bfe01473
Create Date: 2026-03-20 20:52:03.277176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '344fc75860e6'
down_revision: Union[str, Sequence[str], None] = '8f61bfe01473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('exam_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'exam_date')
    # ### end Alembic commands ###
