"""add subject_units unit_topics unit_exam_attempts

Revision ID: 5c5889b64290
Revises: 344fc75860e6
Create Date: 2026-03-21 09:04:53.127407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c5889b64290'
down_revision: Union[str, Sequence[str], None] = '344fc75860e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
