"""add extracted_text to resources

Revision ID: e113670811e2
Revises: a8afaf172550
Create Date: 2026-03-06 07:22:30.863295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e113670811e2'
down_revision: Union[str, Sequence[str], None] = 'a8afaf172550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('extracted_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'extracted_text')
    # ### end Alembic commands ###
